;; Copyright (c) 2014 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices ti ads4149 registers)
  #:use-module (bitops)
  #:use-module (chip-remote register-map))

(define-register-map ads4149
  (#x0 (default-value . #x0)
       (contents (readout 0 1)
                 (reset 1 1)))
  (#x1 (default-value . #x0)
       (contents (lvds-swing 2 6)))
  (#x3 (default-value . #x0)
       (contents (high-performance-mode-1 0 2)))
  (#x25 (default-value . #x0)
        (contents (test-patterns 0 3)
                  (disable-gain 3 1)
                  (gain 4 4)))
  (#x26 (default-value . #x0)
        (contents (lvds-data-strength 0 1)
                  (lvds-clkout-strength 1 1)))
  (#x3d (default-value . #x0)
        (contents (enable-offset-correction 5 1)
                  (data-format 6 2)))
  (#x3f (default-value . #x0)
        (contents (custom-pattern-high 0 8)))
  (#x40 (default-value . #x0)
        (contents (custom-pattern-low 2 6)))
  (#x41 (default-value . #x0)
        (contents (en-clkout-fall 0 1)
                  (clkout-rise-posn 1 2)
                  (en-clkout-rise 3 1)
                  (cmos-clkout-strength 4 2)
                  (lvds-cmos 6 2)))
  (#x42 (default-value . #x0)
        (contents (standby 2 1)
                  (disable-low-latency 3 1)
                  (clkout-fall-posn 6 2)))
  (#x43 (default-value . #x0)
        (contents (enable-lvds-swing 0 2)
                  (power-down-out-buf 4 1)
                  (power-down-global 6 1)))
  (#x4a (default-value . #x0)
        (contents (high-performance-mode-2 0 2)))
  (#xbf (default-value . #x0)
        (contents (offset-pedestal 2 6)))
  (#xcf (default-value . #x0)
        (contents (offset-correction-time-constant 2 4)
                  (freeze-offset-correction 7 1)))
  (#xdf (default-value . #x0)
        (contents (low-speed 4 2))))
