;; Copyright (c) 2017-2021 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices bosch bno055)
  #:use-module (chip-remote codecs)
  #:use-module (chip-remote device)
  #:use-module (chip-remote manufacturer bosch)
  #:use-module (chip-remote item)
  #:use-module (chip-remote page-map)
  #:use-module (chip-remote register)
  #:use-module (chip-remote register-map)
  #:use-module (chip-remote utilities)
  #:export (bno055))

(define-register-map bno055-page-0
  (table
   (↔ (#x00 († (‣ bno055-chip-id 0 8)))
      (#x01 († (‣ acc-chip-id 0 8)))
      (#x02 († (‣ mag-chip-id 0 8)))
      (#x03 († (‣ gyr-chip-id 0 8)))
      (#x04 († (‣ software-revision-lsb 0 8)))
      (#x05 († (‣ software-revision-msb 0 8)))
      (#x06 († (‣ bootloader-revision 0 8)))
      ;; Interesting thing about register 7: This is the page-id register, that's
      ;; present in both memory pages. We'll figure out how to deal with this.
      (#x07 († (‣ page-id 0 8)))
      (#x08 († (‣ acc-data-x-lsb 0 8)))
      (#x09 († (‣ acc-data-x-msb 0 8)))
      (#x0a († (‣ acc-data-y-lsb 0 8)))
      (#x0b († (‣ acc-data-y-msb 0 8)))
      (#x0c († (‣ acc-data-z-lsb 0 8)))
      (#x0d († (‣ acc-data-z-msb 0 8)))
      (#x0e († (‣ mag-data-x-lsb 0 8)))
      (#x0f († (‣ mag-data-x-msb 0 8)))
      (#x10 († (‣ mag-data-y-lsb 0 8)))
      (#x11 († (‣ mag-data-y-msb 0 8)))
      (#x12 († (‣ mag-data-z-lsb 0 8)))
      (#x13 († (‣ mag-data-z-msb 0 8)))
      (#x14 († (‣ gyr-data-x-lsb 0 8)))
      (#x15 († (‣ gyr-data-x-msb 0 8)))
      (#x16 († (‣ gyr-data-y-lsb 0 8)))
      (#x17 († (‣ gyr-data-y-msb 0 8)))
      (#x18 († (‣ gyr-data-z-lsb 0 8)))
      (#x19 († (‣ gyr-data-z-msb 0 8)))
      (#x1a († (‣ euler-heading-lsb 0 8)))
      (#x1b († (‣ euler-heading-msb 0 8)))
      (#x1c († (‣ euler-roll-lsb 0 8)))
      (#x1d († (‣ euler-roll-msb 0 8)))
      (#x1e († (‣ euler-pitch-lsb 0 8)))
      (#x1f († (‣ euler-pitch-msb 0 8)))
      (#x20 († (‣ quaternion-w-lsb 0 8)))
      (#x21 († (‣ quaternion-w-msb 0 8)))
      (#x22 († (‣ quaternion-x-lsb 0 8)))
      (#x23 († (‣ quaternion-x-msb 0 8)))
      (#x24 († (‣ quaternion-y-lsb 0 8)))
      (#x25 († (‣ quaternion-y-msb 0 8)))
      (#x26 († (‣ quaternion-z-lsb 0 8)))
      (#x27 († (‣ quaternion-z-msb 0 8)))
      (#x28 († (‣ linear-accel-data-x-lsb 0 8)))
      (#x29 († (‣ linear-accel-data-x-msb 0 8)))
      (#x2a († (‣ linear-accel-data-y-lsb 0 8)))
      (#x2b († (‣ linear-accel-data-y-msb 0 8)))
      (#x2c († (‣ linear-accel-data-z-lsb 0 8)))
      (#x2d († (‣ linear-accel-data-z-msb 0 8)))
      (#x2e († (‣ gravity-data-x-lsb 0 8)))
      (#x2f († (‣ gravity-data-x-msb 0 8)))
      (#x30 († (‣ gravity-data-y-lsb 0 8)))
      (#x31 († (‣ gravity-data-y-msb 0 8)))
      (#x32 († (‣ gravity-data-z-lsb 0 8)))
      (#x33 († (‣ gravity-data-z-msb 0 8)))
      (#x34 († (‣ temperature 0 8)))
      (#x35 († (‣ mag-calibration-status 0 2)
               (‣ acc-calibration-status 2 2)
               (‣ gyr-calibration-status 4 2)
               (‣ system-calibration-status 6 2)))
      (#x36 († (‣ acc-self-test-result 0 1)
               (‣ mag-self-test-result 1 1)
               (‣ gyr-self-test-result 2 1)
               (‣ mcu-self-test-result 3 1)
               (‣ reserved 4 4)))
      (#x37 († (‣ reserved 0 2)
               (‣ irq-gyr-any-motion 2 1)
               (‣ irq-gyr-high-rate 3 1)
               (‣ reserved 4 1)
               (‣ irq-acc-high-accel 5 1)
               (‣ irq-acc-any-motion 6 1)
               (‣ irq-acc-no-motion 7 1)))
      (#x38 († (‣ sys-clock-cfg-unlock 0 1)
               (‣ reserved 1 7)))
      (#x39 († (‣ system-status-code 0 8)))
      (#x3a († (‣ system-error-code 0 8)))
      (#x3b († (‣ acc-unit-select 0 1)
               (‣ gyr-unit-select 1 1)
               (‣ euler-unit-select 2 1)
               (‣ reserved 3 1)
               (‣ temperature-unit-select 4 1)
               (‣ reserved 5 2)
               (‣ orientation-mode-select 7 1)))
      ;; #x3c is completely reserved.
      (#x3d († (‣ operation-mode 0 4)
               (‣ reserved 4 4)))
      (#x3e († (‣ power-mode 0 2)
               (‣ reserved 2 6)))
      (#x3f († (‣ sys-trigger-self-test 0 1)
               (‣ reserved 1 4)
               (‣ sys-trigger-reset 5 1)
               (‣ sys-trigger-irq-reset 6 1)
               (‣ sys-clock-select 7 1)))
      (#x40 († (‣ sys-temperature-src-select 0 2)
               (‣ reserved 2 6)))
      (#x41 († (‣ axis-map-x 0 2)
               (‣ axis-map-y 2 2)
               (‣ axis-map-z 4 2)
               (‣ reserved 6 2)))
      (#x42 († (‣ axis-map-x-sign 0 1)
               (‣ axis-map-y-sign 1 1)
               (‣ axis-map-z-sign 2 1)
               (‣ reserved 3 5)))
      ;; #x43 .. #x54 are completely reserved.
      (#x55 († (‣ acc-offset-x-lsb 0 8)))
      (#x56 († (‣ acc-offset-x-msb 0 8)))
      (#x57 († (‣ acc-offset-y-lsb 0 8)))
      (#x58 († (‣ acc-offset-y-msb 0 8)))
      (#x59 († (‣ acc-offset-z-lsb 0 8)))
      (#x5a († (‣ acc-offset-z-msb 0 8)))
      (#x5b († (‣ mag-offset-x-lsb 0 8)))
      (#x5c († (‣ mag-offset-x-msb 0 8)))
      (#x5d († (‣ mag-offset-y-lsb 0 8)))
      (#x5e († (‣ mag-offset-y-msb 0 8)))
      (#x5f († (‣ mag-offset-z-lsb 0 8)))
      (#x60 († (‣ mag-offset-z-msb 0 8)))
      (#x61 († (‣ gyr-offset-x-lsb 0 8)))
      (#x62 († (‣ gyr-offset-x-msb 0 8)))
      (#x63 († (‣ gyr-offset-y-lsb 0 8)))
      (#x64 († (‣ gyr-offset-y-msb 0 8)))
      (#x65 († (‣ gyr-offset-z-lsb 0 8)))
      (#x66 († (‣ gyr-offset-z-msb 0 8)))
      (#x67 († (‣ acc-radius-lsb 0 8)))
      (#x67 († (‣ acc-radius-msb 0 8)))
      (#x69 († (‣ mag-radius-lsb 0 8)))
      (#x6a († (‣ mag-radius-msb 0 8))))))

(define-register-map bno055-page-1
  (table
   ;; #x0 .. #x6 is completely reserved.
   (↔ (#x07 († (‣ page-id 0 8)))
      ;; TODO: The data sheet is contradicting itself here. Range could be 3 or two
      ;; bits; so can the bandwidth. Need to figure this out later.
      (#x08 († (‣ acc-range 0 2)
               (‣ acc-bandwidth 2 3)
               (‣ acc-power-mode 5 3)))
      (#x09 († (‣ mag-data-output-rate 0 3)
               (‣ mag-operation-mode 3 2)
               (‣ mag-power-mode 5 2)
               (‣ reserved 7 1)))
      (#x0a († (‣ gyr-range 0 3)
               (‣ gyr-bandwidth 3 3)
               (‣ reserved 6 2)))
      (#x0b († (‣ gyr-power-mode 0 3)
               (‣ reserved 3 5)))
      (#x0c († (‣ acc-sleep-mode 0 1)
               (‣ acc-sleep-duration 1 4)
               (‣ reserved 5 3)))
      (#x0d († (‣ gyr-sleep-duration 0 3)
               (‣ gyr-auto-sleep-duration 3 3)
               (‣ reserved 6 2)))
      ;; #xe is completely reserved.
      (#x0f († (‣ reserved 0 2)
               (‣ irq-mask-gyr-any-motion 2 1)
               (‣ irq-mask-gyr-high-rate 3 1)
               (‣ reserved 4 1)
               (‣ irq-mask-acc-high-accel 5 1)
               (‣ irq-mask-acc-any-motion 6 1)
               (‣ irq-mask-acc-no-motion 7 1)))
      (#x10 († (‣ reserved 0 2)
               (‣ irq-enable-gyr-any-motion 2 1)
               (‣ irq-enable-gyr-high-rate 3 1)
               (‣ reserved 4 1)
               (‣ irq-enable-acc-high-accel 5 1)
               (‣ irq-enable-acc-any-motion 6 1)
               (‣ irq-enable-acc-no-motion 7 1)))
      (#x11 († (‣ acc-any-motion-threshold 0 8)))
      (#x12 († (‣ acc-any-motion-duration 0 2)
               (‣ acc-any/no-motion-x-axis 2 1)
               (‣ acc-any/no-motion-y-axis 3 1)
               (‣ acc-any/no-motion-z-axis 4 1)
               (‣ acc-high-accel-x-axis 5 1)
               (‣ acc-high-accel-y-axis 6 1)
               (‣ acc-high-accel-z-axis 7 1)))
      (#x13 († (‣ acc-high-accel-duration 0 8)))
      (#x14 († (‣ acc-high-accel-threshold 0 8)))
      (#x15 († (‣ acc-slow/no-motion-threshold 0 8)))
      (#x16 († (‣ acc-slow/no-motion-select 0 1)
               (‣ acc-slow/no-motion-duration 1 6)
               (‣ reserved 7 1)))
      (#x17 († (‣ gyr-any-motion-x-axis 0 1)
               (‣ gyr-any-motion-y-axis 1 1)
               (‣ gyr-any-motion-z-axis 2 1)
               (‣ gyr-high-rate-x-axis 3 1)
               (‣ gyr-high-rate-y-axis 4 1)
               (‣ gyr-high-rate-z-axis 5 1)
               (‣ gyr-any-motion-select-filtered 6 1)
               (‣ gyr-high-rate-select-filtered 7 1)))
      (#x18 († (‣ gyr-high-rate-x-threshold 0 5)
               (‣ gyr-high-rate-x-threshold-hysteresis 5 2)
               (‣ reserved 7 1)))
      (#x19 († (‣ gyr-high-rate-x-duration 0 8)))
      (#x1a († (‣ gyr-high-rate-y-threshold 0 5)
               (‣ gyr-high-rate-y-threshold-hysteresis 5 2)
               (‣ reserved 7 1)))
      (#x1b († (‣ gyr-high-rate-y-duration 0 8)))
      (#x1c († (‣ gyr-high-rate-z-threshold 0 5)
               (‣ gyr-high-rate-z-threshold-hysteresis 5 2)
               (‣ reserved 7 1)))
      (#x1d († (‣ gyr-high-rate-z-duration 0 8)))
      (#x1e († (‣ gyr-any-motion-threshold 0 7)
               (‣ reserved 7 1)))
      (#x1f († (‣ gyr-any-motion-slope-samples 0 2)
               (‣ gyr-any-motion-awake-duration 2 2)
               (‣ reserved 4 4)))
      ;; #x20 .. #x4f are completely reserved.
      ;;
      ;; 16 bytes of unique ID:
      ;;   OOppNNmmLLkkJJiiHHggFFeeDDccBBaa
      (#x50 († (‣ bno055-unique-id-a 0 8)))
      (#x51 († (‣ bno055-unique-id-b 0 8)))
      (#x52 († (‣ bno055-unique-id-c 0 8)))
      (#x53 († (‣ bno055-unique-id-d 0 8)))
      (#x54 († (‣ bno055-unique-id-e 0 8)))
      (#x55 († (‣ bno055-unique-id-f 0 8)))
      (#x56 († (‣ bno055-unique-id-g 0 8)))
      (#x57 († (‣ bno055-unique-id-h 0 8)))
      (#x58 († (‣ bno055-unique-id-i 0 8)))
      (#x59 († (‣ bno055-unique-id-j 0 8)))
      (#x5a († (‣ bno055-unique-id-k 0 8)))
      (#x5b († (‣ bno055-unique-id-l 0 8)))
      (#x5c († (‣ bno055-unique-id-m 0 8)))
      (#x5d († (‣ bno055-unique-id-n 0 8)))
      (#x5e († (‣ bno055-unique-id-o 0 8)))
      (#x5f († (‣ bno055-unique-id-p 0 8))))))

(define-page-map bno055-page-map
  (table
   (↔ (0 bno055-page-0)
      (1 bno055-page-1))))

(define-device bno055
  (manufacturer bosch)
  (homepage "https://www.bosch-sensortec.com/bst/products/all_products/bno055")
  (datasheet "https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST_BNO055_DS000_14.pdf")
  (keywords '(nine axis absolute orientation sensor motion unit))
  (register-width 8)
  (page-map bno055-page-map))
