;; Copyright (c) 2018 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices decawave dw1000)
  #:use-module (chip-remote device)
  #:use-module (chip-remote register)
  #:use-module (chip-remote manufacturer decawave)
  #:use-module (chip-remote devices decawave dw1000 registers)
  #:export (dw1000))

(define-device dw1000
  #:manufacturer decawave
  #:homepage "https://www.decawave.com/products/dw1000"
  #:datasheet "https://www.decawave.com/sites/default/files/DW1000-Datasheet-V2.15.pdf"
  #:keywords '(uwb tranceiver ieee802.15.4-2011 positioning location)
  #:register-map (#:table* (#x00 reg:device-id)
                           (#x01 reg:ieee-eui)
                           (#x03 reg:pan-id/short-address)
                           (#x04 reg:system-cfg)
                           (#x06 reg:system-time)
                           (#x08 reg:tx-frame-ctrl)
                           (#x09 reg:tx-buffer)
                           (#x0a reg:delayed-tx/rx-time)
                           (#x0c reg:rx-frame-wait-timeout)
                           (#x0d reg:system-ctrl)
                           (#x0e reg:system-event-mask)
                           (#x0f reg:system-status)
                           (#x10 reg:rx-frame-info)
                           (#x11 reg:rx-buffer)
                           (#x12 reg:rx-frame-quality-info)
                           (#x13 reg:rx-time-track-interval)
                           (#x14 reg:rx-time-track-offset)
                           (#x15 reg:rx-time-of-arrival)
                           (#x17 reg:tx-time-of-sending)
                           (#x18 reg:tx-antenna-delay)
                           (#x19 reg:system-state)
                           (#x1a reg:ack-time/response-time)
                           (#x1d reg:rx-sniff-mode-cfg)
                           (#x1e reg:tx-power-ctrl)
                           (#x1f reg:channel-ctrl)
                           (#x21 reg:user-sfd-sequences)
                           (#x23 reg:agc-ctrl)
                           (#x24 reg:external-sync-ctrl)
                           (#x25 reg:accumulator-memory)
                           (#x26 reg:gpio-ctrl)
                           (#x27 reg:digital-rx-cfg)
                           (#x28 reg:analog-rx-cfg)
                           (#x2a reg:tx-calibration-cfg)
                           (#x2b reg:frequency-synthesizer-ctrl)
                           (#x2c reg:always-on-ctrl)
                           (#x2d reg:otp-interface)
                           (#x2e reg:leading-edge-detect-ctrl)
                           (#x2f reg:digital-diagnostics)
                           (#x36 reg:power-management-ctrl)))
