;; Copyright (c) 2023 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices decawave dw3000)
  #:use-module (chip-remote device)
  #:use-module (chip-remote register-map)
  #:use-module (chip-remote page-map)
  #:use-module (chip-remote manufacturer decawave)
  #:use-module (chip-remote utilities)
  #:use-module (chip-remote devices decawave dw3000 registers)
  #:export (dw3000))

(define-device dw3000
  (manufacturer decawave)
  (homepage "https://www.qorvo.com/products/p/DW3220")
  (datasheet "https://www.qorvo.com/products/d/da008154")
  (keywords '(uwb tranceiver ieee802.15.4z positioning location))
  (page-map (pm→ (table (↔ (#x00 page:general-cfg-0)
                           (#x01 page:general-cfg-1)
                           (#x02 page:sts-cfg)
                           (#x03 page:receiver-tuning)
                           (#x04 page:external-sync-and-rx-calibration)
                           (#x05 page:gpio-ctrl)
                           (#x06 page:digital-rx-cfg)
                           (#x07 page:analog-rf-cfg)
                           (#x08 page:tx-calibration)
                           (#x09 page:frequency-synth-ctrl)
                           (#x0a page:always-on-system-control)
                           (#x0b page:opt-interface)
                           (#x0c page:channel-impulse-analyzer-0)
                           (#x0d page:channel-impulse-analyzer-1)
                           (#x0e page:channel-impulse-analyzer-2)
                           (#x0f page:digital-diagnostics)
                           (#x11 page:power-management-ctrl-block)
                           (#x12 page:rx-buffer-0)
                           (#x13 page:rx-buffer-1)
                           (#x14 page:tx-buffer)
                           (#x15 page:accumulator-cir-memory)
                           (#x16 page:indirect-pointer-cfg&fast-status))))))
