;; Copyright (c) 2015 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote compiler level-two)
  #:use-module (chip-remote compiler)
  #:export (generate-level-two))

;; "Encoders" are functions that take at least user-readable value and a
;; register value and encode the actual bit representation of the value at the
;; right position within the register value. The latter part is done by using
;; the appropriate function from the API generated by (chip-remote compiler
;; level-one).

(define (generate-encoders keyword data)
  '())

(define (generate-decoders keyword data)
  '())

(define-syntax generate-level-two
  (lambda (x)
    (syntax-case x ()
      ((kw file)
       (let* ((fname (determine-file-name (syntax->datum #'file)))
              (data (analyse-register-map #'kw (read-file #'kw fname))))
         (with-syntax (((encoders ...) (generate-encoders #'kw data))
                       ((decoders ...) (generate-decoders #'kw data)))
           #'(begin encoders ...
                    decoders ...)))))))
