(use-modules (termios)
             (termios system)
             (chip-remote bit-operations)
             (chip-remote codecs)
             (chip-remote combination)
             (chip-remote commander)
             (chip-remote decode)
             (chip-remote decode to-c-values)
             (chip-remote decode to-text)
             (chip-remote decode types)
             (chip-remote device)
             (chip-remote device access)
             (chip-remote device spi)
             (chip-remote device transmit)
             (chip-remote interact)
             (chip-remote interpreter)
             (chip-remote io)
             (chip-remote item)
             (chip-remote item access)
             (chip-remote item builder)
             (chip-remote manufacturer)
             (chip-remote manufacturer analog-devices)
             (chip-remote manufacturer bosch)
             (chip-remote manufacturer decawave)
             (chip-remote manufacturer invensense)
             (chip-remote manufacturer linear-technology)
             (chip-remote manufacturer microchip)
             (chip-remote manufacturer texas-instruments)
             (chip-remote modify)
             (chip-remote named-value)
             (chip-remote page-map)
             (chip-remote process-plist)
             (chip-remote protocol)
             (chip-remote register)
             (chip-remote register common)
             (chip-remote register modifiers)
             (chip-remote register predicates)
             (chip-remote register-window)
             (chip-remote register-map)
             (chip-remote register-map utilities)
             (chip-remote semantics)
             (chip-remote simplify)
             (chip-remote type-operations)
             ;;(chip-remote units)
             (chip-remote utilities)
             (chip-remote validate)
             ;; Analog Devices
             (chip-remote devices analog-devices adf4158)
             ((chip-remote devices analog-devices adf4158 registers) #:prefix adf4158:)
             ((chip-remote devices analog-devices adf4158 tables) #:prefix adf4158:)
             (chip-remote devices analog-devices adf4169)
             ((chip-remote devices analog-devices adf4169 registers) #:prefix adf4169:)
             ((chip-remote devices analog-devices adf4169 tables) #:prefix adf4169:)
             ;; Bosch
             (chip-remote devices bosch bme280)
             ((chip-remote devices bosch bme280 registers) #:prefix bme280:)
             ((chip-remote devices bosch bme280 tables) #:prefix bme280:)
             (chip-remote devices bosch bno055)
             ;; Decawave
             (chip-remote devices decawave dw1000)
             ((chip-remote devices decawave dw1000 registers) #:prefix dw1000:)
             ((chip-remote devices decawave dw1000 tables) #:prefix dw1000:)
             ;; Invensense
             (chip-remote devices invensense icm-20602)
             ;; Linear Technology
             (chip-remote devices linear-technology ltc6603)
             ;; Microchip
             (chip-remote devices microchip mcp4351)
             ((chip-remote devices microchip mcp4351 registers) #:prefix mcp4351:)
             ;; Texas Instruments
             (chip-remote devices texas-instruments ads4149)
             (chip-remote devices texas-instruments cdce72010))

;; Set up a serial connection if CR_SERIAL_DEVICE is set in the execution
;; environment. ‘s’ will be the name of the device, ‘c’ is the associated
;; chip-remote connection object.
(define s (getenv "CR_SERIAL_DEVICE"))
(define c #f)

(when s
  (let ((tty (open-io-file s))
        (ts (make-termios-struct)))
    (cf-make-raw! ts)
    (cf-set-speed! ts termios-B19200)
    (tc-set-attr tty ts)
    (close-port tty))
  (set! c (make-cr-connection s))
  (io-open c))
