;; Copyright (c) 2017-2021 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices invensense icm-20602)
  #:use-module (chip-remote codecs)
  #:use-module (chip-remote device)
  #:use-module (chip-remote manufacturer invensense)
  #:use-module (chip-remote item)
  #:use-module (chip-remote page-map)
  #:use-module (chip-remote register)
  #:use-module (chip-remote register-map)
  #:use-module (chip-remote utilities)
  #:export (icm-20602))

(define-register-map icm-20602-registers
  (table
   (↔ (#x04 († (‣ gyro-x-offset-high 0 2)
               (‣ gyro-x-lownoise-to-lowpower-offset 2 6)))
      (#x05 († (‣ gyro-x-offset-low  0 8)))
      (#x07 († (‣ gyro-y-offset-high 0 2)
               (‣ gyro-y-lownoise-to-lowpower-offset 2 6)))
      (#x08 († (‣ gyro-y-offset-low  0 8)))
      (#x0a († (‣ gyro-z-offset-high 0 2)
               (‣ gyro-z-lownoise-to-lowpower-offset 2 6)))
      (#x0b († (‣ gyro-z-offset-low  0 8)))
      (#x0d († (‣ accel-x-selftest-data 0 8)))
      (#x0e († (‣ accel-y-selftest-data 0 8)))
      (#x0f († (‣ accel-z-selftest-data 0 8)))
      (#x13 († (‣ gyro-x-offset-adjust-high 0 8)))
      (#x14 († (‣ gyro-x-offset-adjust-low  0 8)))
      (#x15 († (‣ gyro-y-offset-adjust-high 0 8)))
      (#x16 († (‣ gyro-y-offset-adjust-low  0 8)))
      (#x17 († (‣ gyro-z-offset-adjust-high 0 8)))
      (#x18 († (‣ gyro-z-offset-adjust-low  0 8)))
      (#x19 († (‣ sample-rate-divider   0 8)))
      (#x1a († (‣ digital-lowpass-cfg   0 3)
               (‣ external-sync-set     3 3)
               (‣ fifo-mode             6 1)
               (‣ default-configuration 7 1 (default 1))))
      (#x1b († (‣ frequency-choice         0 2)
               (‣ reserved                 2 1)
               (‣ gyro-full-scale-select   3 2)
               (‣ gyro-z-self-test-enable? 5 1)
               (‣ gyro-y-self-test-enable? 6 1)
               (‣ gyro-x-self-test-enable? 7 1)))
      (#x1c († (‣ reserved                  0 3)
               (‣ accel-full-scale-select   3 2)
               (‣ accel-z-self-test-enable? 5 1)
               (‣ accel-y-self-test-enable? 6 1)
               (‣ accel-x-self-test-enable? 7 1)))
      (#x1d († (‣ accel-lowpass-cfg              0 3)
               (‣ accel-frequency-choice-enable? 3 1)
               (‣ accel-lowpower-avg-cfg         4 2)
               (‣ reserved                       6 2)))
      (#x1e († (‣ reserved              0 4)
               (‣ gyro-lowpower-avg-cfg 4 3)
               (‣ gyro-lowpower-enable? 7 1)))
      (#x20 († (‣ accel-x-wake-on-threshold 0 8)))
      (#x21 († (‣ accel-y-wake-on-threshold 0 8)))
      (#x22 († (‣ accel-z-wake-on-threshold 0 8)))
      (#x23 († (‣ reserved            0 3)
               (‣ accel-fifo-enable?  3 1)
               (‣ gyro-fifo-enable?   4 1)
               (‣ reserved            5 3)))
      (#x36 († (‣ reserved            0 7)
               (‣ frame-sync-irq-status 7 1)))
      (#x37 († (‣ reserved                    0 2)
               (‣ frame-sync-int-mode-enable? 2 1)
               (‣ frame-sync-int-level        3 1)
               (‣ int-clear-on-any-read?      4 1)
               (‣ latch-int-enable?           5 1)
               (‣ int-mode-open-drain?        6 1)
               (‣ int-boolean/active-low?     7 1)))
      (#x39 († (‣ reserved                    0 6)
               (‣ fifo-watermark-irq-status   6 1)
               (‣ reserved                    7 1)))
      (#x3a († (‣ data-ready-irq-status           0 1)
               (‣ reserved                        1 1)
               (‣ gyro-drive-sys-ready-irq-status 2 1)
               (‣ reserved                        3 1)
               (‣ fifo-overflow-irq-status        4 1)
               (‣ wake-on-motion-z-irq-status     5 1)
               (‣ wake-on-motion-y-irq-status     6 1)
               (‣ wake-on-motion-x-irq-status     7 1)))
      (#x3b († (‣ accel-x-data-high 0 8)))
      (#x3c († (‣ accel-x-data-low  0 8)))
      (#x3d († (‣ accel-y-data-high 0 8)))
      (#x3e († (‣ accel-y-data-low  0 8)))
      (#x3f († (‣ accel-z-data-high 0 8)))
      (#x40 († (‣ accel-z-data-low  0 8)))
      (#x41 († (‣ temperature-data-high 0 8)))
      (#x42 († (‣ temperature-data-low  0 8)))
      (#x43 († (‣ gyro-x-data-high 0 8)))
      (#x44 († (‣ gyro-x-data-low  0 8)))
      (#x45 († (‣ gyro-y-data-high 0 8)))
      (#x46 († (‣ gyro-y-data-low  0 8)))
      (#x47 († (‣ gyro-z-data-high 0 8)))
      (#x48 († (‣ gyro-z-data-low  0 8)))
      (#x50 († (‣ gyro-x-selftest-data 0 8)))
      (#x51 († (‣ gyro-y-selftest-data 0 8)))
      (#x52 († (‣ gyro-z-selftest-data 0 8)))
      (#x60 († (‣ fifo-watermark-threshold-high  0 2)
               (‣ reserved                       2 6)))
      (#x61 († (‣ fifo-watermark-threshold-low   0 8)))
      (#x68 († (‣ temperature-signal-path-reset? 0 1)
               (‣ accel-signal-path-reset?       1 1)
               (‣ reserved                       2 6)))
      (#x69 († (‣ wake-on-motion-threshold-mode  0 1)
               (‣ output-limit                   1 1)
               (‣ reserved                       2 4)
               (‣ accel-sample-compare-mode?     6 1)
               (‣ accel-wake-on-motion-detect?   7 1)))
      (#x6a († (‣ signal-path-reset-all?         0 1)
               (‣ reserved                       1 1)
               (‣ fifo-reset?                    2 1)
               (‣ reserved                       3 3)
               (‣ fifo-enable?                   6 1)
               (‣ reserved                       7 1)))
      (#x6b († (‣ clock-select                   0 3 (default 1))
               (‣ temperature-sensor-enable?
                  3 1 (semantics boolean/active-low))
               (‣ gyro-standby?                  4 1)
               (‣ accel-cycle-sampling?          5 1)
               (‣ sleep-enable?                  6 1 (default #t))
               (‣ device-reset?                  7 1)))
      (#x6c († (‣ gyro-z-enable?  0 1 (semantics boolean/active-low))
               (‣ gyro-y-enable?  1 1 (semantics boolean/active-low))
               (‣ gyro-x-enable?  2 1 (semantics boolean/active-low))
               (‣ accel-z-enable? 3 1 (semantics boolean/active-low))
               (‣ accel-y-enable? 4 1 (semantics boolean/active-low))
               (‣ accel-x-enable? 5 1 (semantics boolean/active-low))
               (‣ reserved        6 2)))
      (#x70 († (‣ reserved        0 6)
               (‣ i2c-disable?    6 1)
               (‣ reserved        7 1)))
      (#x72 († (‣ fifo-count-high 0 8)))
      (#x73 († (‣ fifo-count-low  0 8)))
      (#x74 († (‣ fifo-data       0 8)))
      (#x75 († (‣ device-identification 0 8 (default #x12))))
      (#x77 († (‣ accel-x-offset-high 0 8)))
      (#x78 († (‣ reserved            0 1)
               (‣ accel-x-offset-low  1 7)))
      (#x7a († (‣ accel-y-offset-high 0 8)))
      (#x7b († (‣ reserved            0 1)
               (‣ accel-y-offset-low  1 7)))
      (#x7d († (‣ accel-z-offset-high 0 8)))
      (#x7e († (‣ reserved            0 1)
               (‣ accel-z-offset-low  1 7))))))

(define-device icm-20602
  (manufacturer invensense)
  (homepage "https://www.invensense.com/products/motion-tracking/6-axis/icm-20602/")
  (datasheet "https://www.invensense.com/wp-content/uploads/2016/10/DS-000176-ICM-20602-v1.0.pdf")
  (keywords '(six axis motion unit))
  (register-width 8)
  (page-map (pm→ (table (↔ (#f icm-20602-registers))))))
