;; Copyright (c) 2014 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices ti lmk04828 registers)
  #:use-module ((chip-remote devices ti lmk04828 conversions)
                #:renamer (symbol-prefix-proc 'conv:))
  #:use-module (chip-remote devices ti lmk04828 tables)
  #:use-module (chip-remote bit-decoders)
  #:use-module (chip-remote register-map)
  #:export (lmk04828-register-width))

(define lmk04828-register-width 8)

(define lmk04828-read-only-registers
  '(#x3 #x4 #x5 #x6 #xc #xd))

(define-register-map lmk04828
  (#x0000 (default-value 0)
          (contents (reset 7 1 => logic-active-high)
                    (spi-three-wire 4 1 => logic-active-low)))
  (#x0002 (default-value 0)
          (contents (powerdown 0 1 => logic-active-high)))
  ;; The following registers are read-only...
  (#x0003 (default-value 6)
          (contents (id-device-type 0 8)))
  (#x0004 (default-value 208)
          (contents (id-prod-high 0 8)))
  (#x0005 (default-value 91)
          (contents (id-prod-low 0 8)))
  (#x0006 (default-value 32)
          (contents (id-maskrev 0 8)))
  (#x000c (default-value 81)
          (contents (id-vndr-high 0 8)))
  (#x000d (default-value 4)
          (contents (id-vndr-low 0 8)))
  ;; ...up to here.
  ;;
  ;; Then #x0100...#x0137 are Device Clock and SYSREF Clock Output Controls.
  ;;
  ;; - ODL: Output-Drive-Level
  ;; - IDL: Input-Drive-Level
  ;; - DIV: Divider
  ;; - DDLY: Digital-Delay
  ;; - ADLY: Analog-Delay
  (#x0100 (default-value 0)
          (contents (clkout0-1-odl 6 1 => logic-active-high)
                    (clkout0-1-idl 5 1 => logic-active-high)
                    (dclkout0-div 0 5 => conv:bits->clkout-divider)))
  (#x0101 (default-value 0)
          (contents (dclkout0-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout0-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x0103 (default-value 0)
          (contents (dclkout0-adly 3 5 => conv:bits->analog-delay)
                    (dclkout0-adly-mux 2 1 => logic-active-high)
                    (dclkout0-mux 0 2 => clkout-mux-map)))
  (#x0104 (default-value 0)
          (contents (dclkout0-hs 6 1 => logic-active-high)
                    (sdclkout1-mux 5 1 => devclk-sysref-map)
                    (sdclkout1-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout1-hs 0 1 => logic-active-high)))
  (#x0105 (default-value 0)
          (contents (sdclkout1-adly-en 4 1 => logic-active-high)
                    (sdclkout1-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x0106 (default-value 0)
          (contents (dclkout0-ddly-pd 7 1 => logic-active-high)
                    (dclkout0-hsg-pd 6 1 => logic-active-high)
                    (dclkout0-adlyg-pd 5 1 => logic-active-high)
                    (dclkout0-adly-pd 4 1 => logic-active-high)
                    (clkout0-1-pd 3 1 => logic-active-high)
                    (sdclkout1-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout1-pd 0 1 => logic-active-high)))
  (#x0107 (default-value 0)
          (contents (sdclkout1-pol 7 1 => output-polarity-map)
                    (clkout1-fmt 4 3 => output-format-map)
                    (dclkout0-pol 3 1 => output-polarity-map)
                    (clkout0-fmt 0 3 => output-format-map)))
  (#x0108 (default-value 0)
          (contents (clkout2-3-odl 6 1 => logic-active-high)
                    (clkout2-3-idl 5 1 => logic-active-high)
                    (dclkout2-div 0 5 => conv:bits->clkout-divider)))
  (#x0109 (default-value 0)
          (contents (dclkout2-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout2-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x010b (default-value 0)
          (contents (dclkout2-adly 3 5 => conv:bits->analog-delay)
                    (dclkout2-adly-mux 2 1 => logic-active-high)
                    (dclkout2-mux 0 2 => clkout-mux-map)))
  (#x010c (default-value 0)
          (contents (dclkout2-hs 6 1 => logic-active-high)
                    (sdclkout3-mux 5 1 => devclk-sysref-map)
                    (sdclkout3-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout3-hs 0 1 => logic-active-high)))
  (#x010d (default-value 0)
          (contents (sdclkout3-adly-en 4 1 => logic-active-high)
                    (sdclkout3-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x010e (default-value 0)
          (contents (dclkout2-ddly-pd 7 1 => logic-active-high)
                    (dclkout2-hsg-pd 6 1 => logic-active-high)
                    (dclkout2-adlyg-pd 5 1 => logic-active-high)
                    (dclkout2-adly-pd 4 1 => logic-active-high)
                    (clkout2-3-pd 3 1 => logic-active-high)
                    (sdclkout3-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout3-pd 0 1 => logic-active-high)))
  (#x010f (default-value 0)
          (contents (sdclkout3-pol 7 1 => output-polarity-map)
                    (clkout3-fmt 4 3 => output-format-map)
                    (dclkout2-pol 3 1 => output-polarity-map)
                    (clkout2-fmt 0 3 => output-format-map)))
  (#x0110 (default-value 0)
          (contents (clkout4-5-odl 6 1 => logic-active-high)
                    (clkout4-5-idl 5 1 => logic-active-high)
                    (dclkout4-div 0 5 => conv:bits->clkout-divider)))
  (#x0111 (default-value 0)
          (contents (dclkout4-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout4-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x0113 (default-value 0)
          (contents (dclkout4-adly 3 5 => conv:bits->analog-delay)
                    (dclkout4-adly-mux 2 1 => logic-active-high)
                    (dclkout4-mux 0 2 => clkout-mux-map)))
  (#x0114 (default-value 0)
          (contents (dclkout4-hs 6 1 => logic-active-high)
                    (sdclkout5-mux 5 1 => devclk-sysref-map)
                    (sdclkout5-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout5-hs 0 1 => logic-active-high)))
  (#x0115 (default-value 0)
          (contents (sdclkout5-adly-en 4 1 => logic-active-high)
                    (sdclkout5-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x0116 (default-value 0)
          (contents (dclkout4-ddly-pd 7 1 => logic-active-high)
                    (dclkout4-hsg-pd 6 1 => logic-active-high)
                    (dclkout4-adlyg-pd 5 1 => logic-active-high)
                    (dclkout4-adly-pd 4 1 => logic-active-high)
                    (clkout4-5-pd 3 1 => logic-active-high)
                    (sdclkout5-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout5-pd 0 1 => logic-active-high)))
  (#x0117 (default-value 0)
          (contents (sdclkout5-pol 7 1 => output-polarity-map)
                    (clkout5-fmt 4 3 => output-format-map)
                    (dclkout4-pol 3 1 => output-polarity-map)
                    (clkout4-fmt 0 3 => output-format-map)))
  (#x0118 (default-value 0)
          (contents (clkout6-7-odl 6 1 => logic-active-high)
                    (clkout6-8-idl 5 1 => logic-active-high)
                    (dclkout6-div 0 5 => conv:bits->clkout-divider)))
  (#x0119 (default-value 0)
          (contents (dclkout6-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout6-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x011b (default-value 0)
          (contents (dclkout6-adly 3 5 => conv:bits->analog-delay)
                    (dclkout6-adly-mux 2 1 => logic-active-high)
                    (dclkout6-mux 0 2 => clkout-mux-map)))
  (#x011c (default-value 0)
          (contents (dclkout6-hs 6 1 => logic-active-high)
                    (sdclkout7-mux 5 1 => devclk-sysref-map)
                    (sdclkout7-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout7-hs 0 1 => logic-active-high)))
  (#x011d (default-value 0)
          (contents (sdclkout7-adly-en 4 1 => logic-active-high)
                    (sdclkout7-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x011e (default-value 0)
          (contents (dclkout6-ddly-pd 7 1 => logic-active-high)
                    (dclkout6-hsg-pd 6 1 => logic-active-high)
                    (dclkout6-adlyg-pd 5 1 => logic-active-high)
                    (dclkout6-adly-pd 4 1 => logic-active-high)
                    (clkout6-7-pd 3 1 => logic-active-high)
                    (sdclkout7-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout7-pd 0 1 => logic-active-high)))
  (#x011f (default-value 0)
          (contents (sdclkout7-pol 7 1 => output-polarity-map)
                    (clkout7-fmt 4 3 => output-format-map)
                    (dclkout6-pol 3 1 => output-polarity-map)
                    (clkout6-fmt 0 3 => output-format-map)))
  (#x0120 (default-value 0)
          (contents (clkout8-9-odl 6 1 => logic-active-high)
                    (clkout8-9-idl 5 1 => logic-active-high)
                    (dclkout8-div 0 5 => conv:bits->clkout-divider)))
  (#x0121 (default-value 0)
          (contents (dclkout8-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout8-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x0123 (default-value 0)
          (contents (dclkout8-adly 3 5 => conv:bits->analog-delay)
                    (dclkout8-adly-mux 2 1 => logic-active-high)
                    (dclkout8-mux 0 2 => clkout-mux-map)))
  (#x0124 (default-value 0)
          (contents (dclkout8-hs 6 1 => logic-active-high)
                    (sdclkout9-mux 5 1 => devclk-sysref-map)
                    (sdclkout9-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout9-hs 0 1 => logic-active-high)))
  (#x0125 (default-value 0)
          (contents (sdclkout9-adly-en 4 1 => logic-active-high)
                    (sdclkout9-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x0126 (default-value 0)
          (contents (dclkout8-ddly-pd 7 1 => logic-active-high)
                    (dclkout8-hsg-pd 6 1 => logic-active-high)
                    (dclkout8-adlyg-pd 5 1 => logic-active-high)
                    (dclkout8-adly-pd 4 1 => logic-active-high)
                    (clkout8-9-pd 3 1 => logic-active-high)
                    (sdclkout9-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout9-pd 0 1 => logic-active-high)))
  (#x0127 (default-value 0)
          (contents (sdclkout9-pol 7 1 => output-polarity-map)
                    (clkout9-fmt 4 3 => output-format-map)
                    (dclkout8-pol 3 1 => output-polarity-map)
                    (clkout8-fmt 0 3 => output-format-map)))
  (#x0128 (default-value 0)
          (contents (clkout10-11-odl 6 1 => logic-active-high)
                    (clkout10-11-idl 5 1 => logic-active-high)
                    (dclkout10-div 0 5 => conv:bits->clkout-divider)))
  (#x0129 (default-value 0)
          (contents (dclkout10-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout10-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x012b (default-value 0)
          (contents (dclkout10-adly 3 5 => conv:bits->analog-delay)
                    (dclkout10-adly-mux 2 1 => logic-active-high)
                    (dclkout10-mux 0 2 => clkout-mux-map)))
  (#x012c (default-value 0)
          (contents (dclkout10-hs 6 1 => logic-active-high)
                    (sdclkout11-mux 5 1 => devclk-sysref-map)
                    (sdclkout11-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout11-hs 0 1 => logic-active-high)))
  (#x012d (default-value 0)
          (contents (sdcklout11-adly-en 4 1 => logic-active-high)
                    (sdclkout11-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x012e (default-value 0)
          (contents (dclkout10-ddly-pd 7 1 => logic-active-high)
                    (dclkout10-hsg-pd 6 1 => logic-active-high)
                    (dlclkout10-adlyg-pd 5 1 => logic-active-high)
                    (dclkout10-adly-pd 4 1 => logic-active-high)
                    (clkout10-11-pd 3 1 => logic-active-high)
                    (sdclkout11-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout11-pd 0 1 => logic-active-high)))
  (#x012f (default-value 0)
          (contents (sdclkout11-pol 7 1 => output-polarity-map)
                    (clkout11-fmt 4 3 => output-format-map)
                    (dclkout10-pol 3 1 => output-polarity-map)
                    (clkout10-fmt 0 3 => output-format-map)))
  (#x0130 (default-value 0)
          (contents (clkout12-13-odl 6 1 => logic-active-high)
                    (clkout12-13-idl 5 1 => logic-active-high)
                    (dclkout12-div 0 5 => conv:bits->clkout-divider)))
  (#x0131 (default-value 0)
          (contents (dclkout12-ddly-cnth 4 4 => conv:bits->digital-delay-cnt)
                    (dclkout12-ddly-cntl 0 4 => conv:bits->digital-delay-cnt)))
  (#x0133 (default-value 0)
          (contents (dclkout12-adly 3 5 => conv:bits->analog-delay)
                    (dclkout12-adly-mux 2 1 => logic-active-high)
                    (dclkout12-mux 0 2 => clkout-mux-map)))
  (#x0134 (default-value 0)
          (contents (dclkout12-hs 6 1 => logic-active-high)
                    (sdclkout13-mux 5 1 => devclk-sysref-map)
                    (sdclkout13-ddly 1 4 => sdclkout-ddelay-map)
                    (sdclkout13-hs 0 1 => logic-active-high)))
  (#x0135 (default-value 0)
          (contents (sdclkout13-adly-en 4 1 => logic-active-high)
                    (sdclkout13-adly 0 4 => conv:bits->sysout-analog-delay)))
  (#x0136 (default-value 0)
          (contents (dclkout12-ddly-pd 7 1 => logic-active-high)
                    (dclkout12-hsg-pd 6 1 => logic-active-high)
                    (dclkout12-adlyg-pd 5 1 => logic-active-high)
                    (dclkout12-adly-pd 4 1 => logic-active-high)
                    (clkout12-13-pd 3 1 => logic-active-high)
                    (sdclkout13-dis-mode 1 2 => sysref-output-state-map)
                    (sdclkout13-pd 0 1 => logic-active-high)))
  (#x0137 (default-value 0)
          (contents (sdclkout13-pol 7 1 => output-polarity-map)
                    (clkout13-fmt 4 3 => output-format-map)
                    (dclkout12-pol 3 1 => output-polarity-map)
                    (clkout12-fmt 0 3 => output-format-map)))
  ;; #x0138...#x0145: SYSREF, SYNC, and Device Config
  (#x0138 (default-value 0)
          (contents (vco-mux 5 2 => vco-mux-map)
                    (oscout-mux 4 1 => oscout-mux-map)
                    (oscout-fmt 0 4 => oscout-format-map)))
  (#x0139 (default-value 0)
          (contents (sysref-mux 0 2 => sysref-mux-map)))
  (#x013a (default-value 0)
          (contents (sysref-div-high 0 5)))
  (#x013b (default-value 0)
          (contents (sysref-div-low 0 8)))
  (#x013c (default-value 0)
          (contents (sysref-ddly-low 0 5)))
  (#x013d (default-value 0)
          (contents (sysref-ddly-high 0 8)))
  (#x013e (default-value 0)
          (contents (sysref-pulse-cnt 0 2)))
  (#x013f (default-value 0)
          (contents (pll2-nclk-mux 4 1)
                    (pll1-nclk-mux 3 1)
                    (fb-mux 1 2)
                    (fb-mux-en 0 1)))
  (#x0140 (default-value 0)
          (contents (pll1-pd 7 1)
                    (vco-ldo-pd 6 1)
                    (vco-pd 5 1)
                    (oscin-pd 4 1)
                    (sysref-gbl-pd 3 1)
                    (sysref-pd 2 1)
                    (sysref-ddly-pd 1 1)
                    (sysref-plsr-pd 0 1)))
  (#x0141 (default-value 0)
          (contents (ddlyd-sysref-en 7 1)
                    (ddlyd12-en 6 1)
                    (ddlyd10-en 5 1)
                    (ddlyd7-en 4 1)
                    (ddlyd6-en 3 1)
                    (ddlyd4-en 2 1)
                    (ddlyd2-en 1 1)
                    (ddlyd0-en 0 1)))
  (#x0142 (default-value 0)
          (contents (ddlyd-step-cnt 0 5)))
  (#x0143 (default-value 0)
          (contents (sysref-ddly-clr 7 1)
                    (sync-1shot-en 6 1)
                    (sync-pol 5 1)
                    (sync-en 4 1)
                    (sync-pll2-dld 3 1)
                    (sync-pll1-dld 2 1)
                    (sync-mode 0 2)))
  (#x0144 (default-value 0)
          (contents (sync-dissysref 7 1)
                    (sync-dis12 6 1)
                    (sync-dis10 5 1)
                    (sync-dis8 4 1)
                    (sync-dis6 3 1)
                    (sync-dis4 2 1)
                    (sync-dis2 1 1)
                    (sync-dis0 0 1)))
  (#x0145 (default-value 0)
          (contents ))
  ;; #x0146...#x0149: CLKin Control
  (#x0146 (default-value 0)
          (contents (clkin2-en 5 1)
                    (clkin1-en 4 1)
                    (clkin0-en 3 1)
                    (clkin2-type 2 1)
                    (clkin1-type 1 1)
                    (clkin0-type 0 1)))
  (#x0147 (default-value 0)
          (contents (clkin-sel-pol 7 1)
                    (clkin-sel-mode 4 3)
                    (clkin1-out-mux 2 2)
                    (clkin0-out-mux 0 2)))
  (#x0148 (default-value 0)
          (contents (clkin-sel0-mux 3 3)
                    (clkin-sel0-type 0 3)))
  (#x0149 (default-value 0)
          (contents (sdio-rdbk-type 6 1)
                    (clkin-sel1-mux 3 3)
                    (clkin-sel1-type 0 3)))
  ;; RESET_MUX, RESET_TYPE
  (#x014a (default-value 0)
          (contents (reset-mux 3 3)
                    (reset-type 0 3)))
  ;; #x014b...#x0152: Holdover
  (#x014b (default-value 0)
          (contents (los-timeout 6 2)
                    (los-en 5 1)
                    (track-en 4 1)
                    (holdover-force 3 1)
                    (man-dac-en 2 1)
                    (man-dac-high 0 2)))
  (#x014c (default-value 0)
          (contents (man-dac-low 0 8)))
  (#x014d (default-value 0)
          (contents (dac-trip-low 0 6)))
  (#x014e (default-value 0)
          (contents (dac-clk-mult 6 2)
                    (dac-trip-high 0 6)))
  (#x014f (default-value 0)
          (contents (dac-clk-cntr 0 8)))
  (#x0150 (default-value 0)
          (contents (holdover-pll1-det 4 1)
                    (holdover-los-det 3 1)
                    (holdover-vtune-det 2 1)
                    (holdover-hitless-switch 1 1)
                    (holdover-en 0 1)))
  (#x0151 (default-value 0)
          (contents (holdover-dld-cnt-high 0 6)))
  (#x0152 (default-value 0)
          (contents (holdover-dld-cnt-low 0 8)))
  ;; #x0153...#x015f: PLL1 Configuration
  (#x0153 (default-value 0)
          (contents (clkin0-r-high 0 6)))
  (#x0154 (default-value 0)
          (contents (clkin0-r-low 0 8)))
  (#x0155 (default-value 0)
          (contents (clkin1-r-high 0 6)))
  (#x0156 (default-value 0)
          (contents (clkin1-r-low 0 8)))
  (#x0157 (default-value 0)
          (contents (clkin2-r-high 0 6)))
  (#x0158 (default-value 0)
          (contents (clkin2-r-low 0 8)))
  (#x0159 (default-value 0)
          (contents (pll1-n-high 0 6)))
  (#x015a (default-value 0)
          (contents (pll1-n-low 0 8)))
  (#x015b (default-value 0)
          (contents (pll1-wnd-size 6 2)
                    (pll1-cp-tri 5 1)
                    (pll1-cp-pol 4 1)
                    (pll1-cp-gain 0 4)))
  (#x015c (default-value 0)
          (contents (pll1-dld-cnt-high 0 6)))
  (#x015d (default-value 0)
          (contents (pll1-dld-cnt-low 0 8)))
  (#x015e (default-value 0)
          (contents (pll1-r-dly 3 3)
                    (pll1-n-dly 0 3)))
  (#x015f (default-value 0)
          (contents (pll1-ld-mux 3 5)
                    (pll1-ld-type 0 3)))
  ;; #x0160...#x016e: PLL2 Configuration
  (#x0160 (default-value 0)
          (contents (pll2-r-high 0 4)))
  (#x0161 (default-value 0)
          (contents (pll2-r-low 0 8)))
  (#x0162 (default-value 0)
          (contents (pll2-p 5 3)
                    (oscin-freq 2 3)
                    (pll2-xtal-en 1 1)
                    (pll2-ref-2x-en 0 1)))
  (#x0163 (default-value 0)
          (contents (pll2-n-cal-high 0 2)))
  (#x0164 (default-value 0)
          (contents (pll2-n-cal-mid 0 8)))
  (#x0165 (default-value 0)
          (contents (pll2-n-cal-low 0 8)))
  (#x0166 (default-value 0)
          (contents (pll2-fcal-dis 2 1)
                    (pll2-n-high 0 2)))
  (#x0167 (default-value 0)
          (contents (pll2-n-mid 0 8)))
  (#x0168 (default-value 0)
          (contents (pll2-n-low 0 8)))
  (#x0169 (default-value 0)
          (contents (pll2-wnd-size 5 2)
                    (pll2-cp-gain 3 2)
                    (pll2-cp-pol 2 1)
                    (pll2-cp-tri 1 1)))
  (#x016a (default-value 0)
          (contents (sysref-req-en 6 1)
                    (pll2-dld-cnt-high 0 6)))
  (#x016b (default-value 0)
          (contents (pll2-dld-cnt-low 0 8)))
  (#x016c (default-value 0)
          (contents (pll2-lf-r4 3 3)
                    (pll2-lf-r3 0 3)))
  (#x016d (default-value 0)
          (contents (pll2-lf-c4 4 4)
                    (pll2-lf-c3 0 4)))
  (#x016e (default-value 0)
          (contents (pll2-ld-mux 3 5)
                    (pll2-ld-type 0 3)))
  ;; #x016f...#x1fff: Misc Registers
  (#x0173 (default-value 0)
          (contents (pll2-pre-pd 6 1)
                    (pll2-pd 5 1)))
  (#x017c (default-value 0)
          (contents (opt-reg-1 0 8)))
  (#x017d (default-value 0)
          (contents (opt-reg-2 0 8)))
  (#x0182 (default-value 0)
          (contents (rb-pll1-ld-lost 2 1)
                    (rb-pll1-ld 1 1)
                    (clr-pll1-ld-lost 0 1)))
  (#x0183 (default-value 0)
          (contents (rb-pll2-ld-lost 2 1)
                    (rb-pll2-ld 1 1)
                    (clr-pll2-ld-lost 0 1)))
  (#x0184 (default-value 0)
          (contents (rb-dac-value-high 6 2)
                    (rb-clkin2-sel 5 1)
                    (rb-clkin1-sel 4 1)
                    (rb-clkin0-sel 3 1)
                    (rb-clkin1-los 1 1)
                    (rb-clkin0-los 0 1)))
  (#x0185 (default-value 0)
          (contents (rb-dac-value-low 0 8)))
  (#x0188 (default-value 0)
          (contents (rb-holdover 4 1)))
  (#x1ffd (default-value 0)
          (contents (spi-lock-high 0 8)))
  (#x1ffe (default-value 0)
          (contents (spi-lock-mid 0 8)))
  (#x1fff (default-value 0)
          (contents (spi-lock-low 0 8))))
