;; Copyright (c) 2023 chip-remote workers, All rights reserved.
;;
;; Terms for redistribution and use can be found in LICENCE.

(define-module (chip-remote devices analog-devices ad9262 tables)
  #:use-module (chip-remote named-value)
  #:export (bw-map
            channel-index-map
            chip-grade-map
            data-rate-map
            driver-map
            driver-18-map
            driver-33-map
            output-format-map
            pll-mult-map
            power-down-map
            threshold-map))

(define-value channel-index-map '((both      . #b00)
                                  (channel-a . #b01)
                                  (channel-b . #b10)
                                  (both      . #b11)))

(define-value chip-grade-map '((bw-10mhz  . #b00)
                               (bw-5mhz   . #b01)
                               (bw-2.5mhz . #b10)
                               (reserved  . #b11)))

(define-value power-down-map '((normal-operation . #b00)
                               (power-down-local . #b01)
                               (standby          . #b10)
                               (sleep            . #b11)))

;; This is from the datasheet's table 10, only that the table ranges the keys
;; from 1…64, which is output range for the six bit item the multiplier is. I
;; assume, what they really mean in this table is item-value+1, so:
(define-value pll-mult-map '(( 8 .  0)
                             ( 8 .  1)
                             ( 8 .  2)
                             ( 8 .  3)
                             ( 8 .  4)
                             ( 8 .  5)
                             ( 8 .  6)
                             ( 8 .  7)
                             ( 9 .  8)
                             (10 .  9)
                             (10 . 10)
                             (12 . 11)
                             (12 . 12)
                             (14 . 13)
                             (15 . 14)
                             (16 . 15)
                             (17 . 16)
                             (18 . 17)
                             (18 . 18)
                             (20 . 19)
                             (21 . 20)
                             (21 . 21)
                             (21 . 22)
                             (24 . 23)
                             (25 . 24)
                             (25 . 25)
                             (25 . 26)
                             (28 . 27)
                             (28 . 28)
                             (30 . 29)
                             (30 . 30)
                             (32 . 31)
                             (32 . 32)
                             (34 . 33)
                             (34 . 34)
                             (34 . 35)
                             (34 . 36)
                             (34 . 37)
                             (34 . 38)
                             (34 . 39)
                             (34 . 40)
                             (42 . 41)
                             (42 . 42)
                             (42 . 43)
                             (42 . 44)
                             (42 . 45)
                             (42 . 46)
                             (42 . 47)
                             (42 . 48)
                             (42 . 49)
                             (42 . 50)
                             (42 . 51)
                             (42 . 52)
                             (42 . 53)
                             (42 . 54)
                             (42 . 55)
                             (42 . 56)
                             (42 . 57)
                             (42 . 58)
                             (42 . 59)
                             (42 . 60)
                             (42 . 61)
                             (42 . 62)
                             (42 . 63)))

;; This is actually clipped by the chip-grade.
(define-value bw-map '((bw-10mhz  . #b00)
                       (bw-5mhz   . #b01)
                       (bw-2.5mhz . #b10)
                       (bw-2.5mhz . #b11)))

(define-value driver-map '((drive-3.3v . 0)
                           (drive-1.8v . 1)))

(define-value driver-18-map '((strength-10mA . #b00)
                              (strength-20mA . #b01)
                              (strength-30mA . #b10)
                              (strength-40mA . #b11)))

(define-value driver-33-map '((strength-33mA  . #b00)
                              (strength-63mA  . #b01)
                              (strength-93mA  . #b10)
                              (strength-120mA . #b11)))

(define-value output-format-map '((offset-binary   . #b00)
                                  (twos-complement . #b01)
                                  (gray-code       . #b10)
                                  (offset-binary   . #b11)))

(define-value data-rate-map '((SRCreset  .  0)
                              (4         .  1)
                              (4         .  2)
                              (4         .  3)
                              (4         .  4)
                              (4         .  5)
                              (4         .  6)
                              (4         .  7)
                              (4         .  8)
                              (4.5       .  9)
                              (5         . 10)
                              (5.5       . 11)
                              (6         . 12)
                              (6.5       . 13)
                              (7         . 14)
                              (7.5       . 15)
                              (8         . 16)
                              (8.5       . 17)
                              (9         . 18)
                              (9.5       . 19)
                              (10        . 20)
                              (10.5      . 21)
                              (11        . 22)
                              (11.5      . 23)
                              (12        . 24)
                              (12.5      . 25)
                              (13        . 26)
                              (13.5      . 27)
                              (14        . 28)
                              (14.5      . 29)
                              (15        . 30)
                              (15.5      . 31)
                              (16        . 32)
                              (16.5      . 33)
                              (17        . 34)
                              (17.5      . 35)
                              (18        . 36)
                              (18.5      . 37)
                              (19        . 38)
                              (19.5      . 39)
                              (20        . 40)
                              (20.5      . 41)
                              (21        . 42)
                              (21        . 43)
                              (22        . 44)
                              (22.5      . 45)
                              (23        . 46)
                              (23.5      . 47)
                              (24        . 48)
                              (24.5      . 49)
                              (25        . 50)
                              (25.5      . 51)
                              (26        . 52)
                              (26.5      . 53)
                              (27        . 54)
                              (27.5      . 55)
                              (28        . 56)
                              (28.5      . 57)
                              (29        . 58)
                              (29.5      . 59)
                              (30        . 60)
                              (30.5      . 61)
                              (31        . 62)
                              (31.5      . 63)))

(define-value threshold-map '((invalid . #x00)
                              (−36.12  . #x01)
                              (−30.10  . #x02)
                              (−26.58  . #x03)
                              (−24.08  . #x04)
                              (−22.14  . #x05)
                              (−20.56  . #x06)
                              (−19.22  . #x07)
                              (−18.06  . #x08)
                              (−17.04  . #x09)
                              (−16.12  . #x0a)
                              (−15.29  . #x0b)
                              (−14.54  . #x0c)
                              (−13.84  . #x0d)
                              (−13.20  . #x0e)
                              (−12.60  . #x0f)
                              (−12.04  . #x10)
                              (−11.51  . #x11)
                              (−11.02  . #x12)
                              (−10.56  . #x13)
                              (−10.10  . #x14)
                              (−9.68   . #x15)
                              (−9.28   . #x16)
                              (−8.89   . #x17)
                              (−8.52   . #x18)
                              (−8.16   . #x19)
                              (−7.82   . #x1a)
                              (−7.50   . #x1b)
                              (−7.18   . #x1c)
                              (−6.88   . #x1d)
                              (−6.58   . #x1e)
                              (−6.30   . #x1f)
                              (−6.02   . #x20)
                              (−5.75   . #x21)
                              (−5.49   . #x22)
                              (−5.24   . #x23)
                              (−5.00   . #x24)
                              (−4.76   . #x25)
                              (−4.53   . #x26)
                              (−4.30   . #x27)
                              (−4.08   . #x28)
                              (−3.87   . #x29)
                              (−3.66   . #x2a)
                              (−3.45   . #x2b)
                              (−3.25   . #x2c)
                              (−3.06   . #x2d)
                              (−2.87   . #x2e)
                              (−2.68   . #x2f)
                              (−2.50   . #x30)
                              (−2.32   . #x31)
                              (−2.14   . #x32)
                              (−1.97   . #x33)
                              (−1.80   . #x34)
                              (−1.64   . #x35)
                              (−1.48   . #x36)
                              (−1.32   . #x37)
                              (−1.16   . #x38)
                              (−1.00   . #x39)
                              (−0.86   . #x3a)
                              (−0.71   . #x3b)
                              (−0.56   . #x3c)
                              (−0.42   . #x3d)
                              (−0.28   . #x3e)
                              (−0.14   . #x3f)))
