#!/bin/sh

mode="$1"
input="$2"
intermediate="${input%.*}"
output="$3"

stripper () {
    sed -e 's@Synopsis:\\hspace{[0-9.]*cm}@Synopsis:@' \
        -e 's@\\noindent{}Example:\\hspace{[0-9.]*cm}@Example:@' \
        -e 's@\\vspace{[0-9.]*cm}\\noindent *@@'
}

case "$mode" in
pdf)
    emacs -Q --batch --visit="$input" --funcall org-latex-export-to-pdf || exit 1
    rm -f "${intermediate}.tex"
    rm -f "${intermediate}.tex~"
    ;;
html)
    stripped="${intermediate}.stripped"
    stripper < "$input" > "$stripped"
    emacs -Q --batch --visit="$stripped" \
          --eval "(require 'org)" \
          --eval "(require 'ox)" \
          --eval "(require 'ox-html)" \
          --funcall org-html-export-to-html || exit 1
    rm -f "$stripped"
    ;;
txt)
    stripped="${intermediate}.stripped"
    stripper < "$input" > "$stripped"
    emacs -Q --batch --visit="$stripped" \
          --eval "(require 'org)" \
          --eval "(require 'ox)" \
          --eval "(require 'ox-ascii)" \
          --eval "(setq org-ascii-charset 'utf-8)" \
          --eval '(setq-default org-ascii-verbatim-format "%s")' \
          --eval '(defun org-ascii-italic (it c in) (format "%s" c))' \
          --eval '(defun org-ascii-bold (b c in) (format "%s" c))' \
          --funcall org-ascii-export-to-ascii || exit 1
    rm -f "$stripped"
    ;;
*)
    printf 'org-export: Unknown mode: `%s'\''. Giving up.\n' "$mode"
    exit 1
    ;;
esac

if [ "${intermediate}"."$mode" != "$output" ]; then
    mv "${intermediate}"."$mode" "$output" || exit 1
fi
rm -f "${intermediate}.${mode}~"
exit 0
